/// @description Init

// Inherit the parent event
event_inherited();

draw_set_font(global.font_16);
text = "SUPER FREAKS 1 ULTIMATE EDITION"
+ "\n"
+ "\nORIGINAL GAME 2006"
+ "\nREMASTERED 2016"
+ "\nULTIMATE EDITION 2023"
+ "\nBy Mr. Freaks"
+ "\nFormerly known as SuperFreaksDev and KrazyScruffy9001"
+ "\n"
+ "\nMADE WITH:"
+ "\nGame Maker Studio 2"
+ "\nMonochrome Shader from GMS2 manual"
+ "\nInput by @JujuAdams and @offalynne"
+ "\nGood pixel art pretending to be bad pixel art"
+ "\nmade with Aseprite"
+ "\nThe Creation of Freaky Freak HD Painting by EngineerKappa"
+ "\nEdibles Provider: Metalefactor"
+ "\nFreakloader Custom Character Loader by defnotreal_"
+ "\n"
+ "\nPROGRAMMING ASSISTANTS:"
+ "\ndefnotreal_"
+ "\nJorJoe05"
+ "\n"
+ "\nPORTING:"
+ "\nJorJoe05"
+ "\n"
+ "\nCHARACTERS BY:"
+ "\nMr. Freaks"
+ "\nKingnormal"
+ "\n"
+ "\nMUSIC:"
+ "\nOriginal music by philRaco and Mr. Freaks"
+ "\nbut mostly phil tbh"
+ "\nMIDI Soundfont: Arachno by Maxime Abbey"
+ "\n"
+ "\nSOUND EFFECTS:"
+ "\nWarner Bros."
+ "\nHanna-Barbara"
+ "\nCartoon Trax"
+ "\nTITLE SCREEN VOICES:"
+ "\nLance Charleson"
+ "\ndefnotreal_"
+ "\n"
+ "\nMARROW PRIME TRAINING MONTAGE CAMEOS:"
+ "\nMr. Shootem Breaks Out - defnotreal"
+ "\nCODE Bunny - Lavie_Azure"
+ "\nNadine in: Diamond in the Grave - Arrietty"
+ "\nBUDD - EngineerKappa"
+ "\nDanger Cliff - Danger Cliff"
+ "\nTurbo Leaper - Riegel25"
+ "\nRound the Mind - philRaco"
+ "\n"
+ "\nPLAYTESTERS AND FRIENDS:"
+ "\nMr. Freaks (I mean I guess I count)"
+ "\nHeather Flaherty"
+ "\nKevin Doherty"
+ "\nMetalefactor"
+ "\nEngineerKappa"
+ "\nHalatnikov"
+ "\nLance Charleson"
+ "\nSpinycemb"
+ "\nMugen Azure"
+ "\nLuke T. aka Thunder Dragon"
+ "\nAlmyriganHero"
+ "\nphilRaco"
+ "\nMotor Drive"
+ "\nJorJoe05"
+ "\nMasterDisaster64"
+ "\nNULL3D"
+ "\nPVic"
+ "\nArrietty"
+ "\nRummySM"
+ "\ndefnotreal_"
+ "\nRiegel25"
+ "\nMoxxie"
+ "\nEthervil"
+ "\nDanger Cliff"
+ "\nLazie_Azure"
+ "\nVioletta Volnutt"
+ "\nColonel Sandwich"
+ "\nSaturn"
+ "\n"
+ "\n...uh"
+ "\nYeah I'm not sure what else to throw in here"
+ "\nThanks for playing, thanks for #sweeping!"
+ "\nand more importantly..."
+ "\nSee You Next Game!"
+ "\n"
+ "\n"
+ "\nOh, right, press confirm to skip the credits."
+ "\nMusic is nice though isn't it?";
text_height = string_height_ext(text, -1, 424);
pos = 1;
my_speed = 0.075;